name: Terraform CI/CD

on:
  push:
    branches:
      - testing

jobs:
  terraform:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.2  # Adjust to your desired version

      - name: Terraform Format and Validate
        run: |
          terraform init
          terraform validate

      - name: TFSec Scan
        run: |
          curl -L -o tfsec https://github.com/tfsec/tfsec/releases/latest/download/tfsec-linux-amd64
          chmod +x tfsec
          ./tfsec .
        continue-on-error: true

      - name: Terraform Plan
        run: |
          terraform plan -out=tfplan
        continue-on-error: true

      - name: Deploy Infrastructure
        if: success()
        run: |
          terraform apply -auto-approve tfplan
        env:
          TF_CLI_ARGS: "-input=false"  # Automatically approve the apply

      - name: Clean Up
        if: success()
        run: |
          rm tfplan
